const types = {
  SET_APP_STATUS: "SET_APP_STATUS",
  SET_INITIAL_STATE: "SET_INITIAL_STATE",
  SET_ENTIRES: "SET_ENTIRES",
  DELETE_ENTRY: "DELETE_ENTRY",
  CREATE_ENTRY: "CREATE_ENTRY",
};

export default types;
