const types = {
  SET_STATUS: "SET_STATUS",
  SET_INITIAL_STATE: "SET_INITIAL_STATE",
  SET_USERS: "SET_USERS",
  SET_ENTIRES: "SET_ENTIRES",
  DELETE_USER: "DELETE_USER",
  DELETE_ENTRY: "DELETE_ENTRY",
  CREATE_ENTRY: "CREATE_ENTRY",
  CREATE_USER: "CREATE_USER",
};

export default types;
